//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace A_4_Client.MyWebFileService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebFile", Namespace="http://schemas.datacontract.org/2004/07/A_4")]
    [System.SerializableAttribute()]
    public partial class WebFile : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string filePathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long fileSizeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fileName {
            get {
                return this.fileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.fileNameField, value) != true)) {
                    this.fileNameField = value;
                    this.RaisePropertyChanged("fileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string filePath {
            get {
                return this.filePathField;
            }
            set {
                if ((object.ReferenceEquals(this.filePathField, value) != true)) {
                    this.filePathField = value;
                    this.RaisePropertyChanged("filePath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long fileSize {
            get {
                return this.fileSizeField;
            }
            set {
                if ((this.fileSizeField.Equals(value) != true)) {
                    this.fileSizeField = value;
                    this.RaisePropertyChanged("fileSize");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MyWebFileService.IWebFileService")]
    public interface IWebFileService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebFileService/GetFileList", ReplyAction="http://tempuri.org/IWebFileService/GetFileListResponse")]
        A_4_Client.MyWebFileService.WebFile[] GetFileList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebFileService/GetFileList", ReplyAction="http://tempuri.org/IWebFileService/GetFileListResponse")]
        System.Threading.Tasks.Task<A_4_Client.MyWebFileService.WebFile[]> GetFileListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebFileService/GetFile", ReplyAction="http://tempuri.org/IWebFileService/GetFileResponse")]
        System.IO.Stream GetFile(string Filename);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebFileService/GetFile", ReplyAction="http://tempuri.org/IWebFileService/GetFileResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> GetFileAsync(string Filename);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWebFileServiceChannel : A_4_Client.MyWebFileService.IWebFileService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebFileServiceClient : System.ServiceModel.ClientBase<A_4_Client.MyWebFileService.IWebFileService>, A_4_Client.MyWebFileService.IWebFileService {
        
        public WebFileServiceClient() {
        }
        
        public WebFileServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebFileServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebFileServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebFileServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public A_4_Client.MyWebFileService.WebFile[] GetFileList() {
            return base.Channel.GetFileList();
        }
        
        public System.Threading.Tasks.Task<A_4_Client.MyWebFileService.WebFile[]> GetFileListAsync() {
            return base.Channel.GetFileListAsync();
        }
        
        public System.IO.Stream GetFile(string Filename) {
            return base.Channel.GetFile(Filename);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> GetFileAsync(string Filename) {
            return base.Channel.GetFileAsync(Filename);
        }
    }
}
